name: Välfärden
on: pull_request

jobs:
  Build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Read LFS Cache
        run: cp -r -Force ../../.git/lfs .git/

      # Fetches changes and replaces LFS pointers with their actual contents
      - name: Pull From LFS
        run: git lfs pull

      - name: Update LFS Cache
        run: cp -r -Force .git/lfs ../../.git/

      - name: Execute Premake
        run: .\premake5.exe vs2019

      - name: Build Debug
        run: msbuild LambdaEngine.sln -p:Configuration=Debug -p:Platform=x64 /warnaserror

      - name: Build Release
        run: msbuild LambdaEngine.sln -p:Configuration=Release -p:Platform=x64 /warnaserror

  Lint:
    runs-on: [self-hosted, benchmarker, Windows, X64]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Execute Premake
        run: .\premake5.exe vs2019

      - name: Generate Lint Report
        run: python .github/workflows/generate-lint-report.py -o cppcheck_report.txt -i Dependencies

      - name: Get file changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Lint Report
        run: python ./.github/workflows/read-lint-report.py --report ./cppcheck_report.txt
          --modified-files $HOME/files_modified.json --added-files $HOME/files_added.json
