name: Välfärden
on: pull_request

jobs:
  Build-LambdaEngine-Debug:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build LambdaEngine Debug
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: LambdaEngine/LambdaEngine.vcxproj
          build-configuration: Debug x64_StaticLib

  Build-LambdaEngine-Release:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build LambdaEngine Release
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: LambdaEngine/LambdaEngine.vcxproj
          build-configuration: Release x64_StaticLib

  Build-CrazyCanvas-Debug:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build CrazyCanvas Debug
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: CrazyCanvas/CrazyCanvas.vcxproj
          build-configuration: Debug x64_StaticLib

  Build-CrazyCanvas-Release:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build CrazyCanvas Release
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: CrazyCanvas/CrazyCanvas.vcxproj
          build-configuration: Release x64_StaticLib

  Build-Sandbox-Debug:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Sandbox Debug
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: Sandbox/Sandbox.vcxproj
          build-configuration: Debug x64_StaticLib

  Build-Sandbox-Release:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Sandbox Release
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: Sandbox/Sandbox.vcxproj
          build-configuration: Release x64_StaticLib

  Build-Client-Debug:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Client Debug
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: Client/Client.vcxproj
          build-configuration: Debug x64_StaticLib

  Build-Client-Release:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Client Release
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: Client/Client.vcxproj
          build-configuration: Release x64_StaticLib

  Build-Server-Debug:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Server Debug
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: Server/Server.vcxproj
          build-configuration: Debug x64_StaticLib

  Build-Server-Release:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build Server Release
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: Server/Server.vcxproj
          build-configuration: Release x64_StaticLib

  Lint:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Execute Premake
        run: .\premake5.exe vs2019

      - name: Generate Lint Report
        run: python .github/workflows/generate-lint-report.py -o cppcheck_report.txt -i Dependencies

      - name: Get file changes
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Lint Report
        run: python ./.github/workflows/read-lint-report.py --report ./cppcheck_report.txt
          --modified-files $HOME/files_modified.json --added-files $HOME/files_added.json
