name: Välfärden
#on: pull_request
# Debugging:
on:
  push:
      branches:
        - benchmarks

jobs:
  Build-Debug-x64:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Execute Premake
      run: .\premake5.exe vs2019

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build Debug x64
      run: msbuild CrazyCanvas/CrazyCanvas.vcxproj -p:Configuration="Debug x64_StaticLib" -p:Platform=x64

  Build-Release-x64:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        ref: master

    - name: Execute Premake
      run: .\premake5.exe vs2019

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Build Release x64
      run: msbuild CrazyCanvas/CrazyCanvas.vcxproj -p:Configuration="Release x64_StaticLib" -p:Platform=x64

  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Generate Lint Report
        uses: deep5050/cppcheck-action@master
        with:
          exclude_check: vendor
          platform: win64
          output_file: ./cppcheck_report

      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Lint Report
        run: python3 ./.github/workflows/read-lint-report.py --report ./cppcheck_report
          --modified-files $HOME/files_modified.json --added-files $HOME/files_added.json
