name: Benchmark
on:
  push:
      branches:
        - master

jobs:
  benchmark:
    runs-on: [self-hosted, benchmarker, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Read LFS Cache
        run: cp -r -Force ../../.git/lfs .git/

      # Fetches changes and replaces LFS pointers with their actual contents
      - name: Pull From LFS
        run: git lfs pull

      - name: Update LFS Cache
        run: cp -r -Force .git/lfs ../../.git/

      - name: Execute Premake
        run: .\premake5.exe vs2019

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Production
        run: msbuild LambdaEngine.sln -p:Configuration=Production -p:Platform=x64 /warnaserror

      - name: Benchmark
        run: python .github/workflows/benchmark.py --bin .\Build\bin\Production-windows-x86_64-x64\CrazyCanvas\CrazyCanvas.exe

      - name: Update Charts
        run: python .github/workflows/update-charts.py
        env:
          PAT: ${{ secrets.DOCS_PAT }}
