name: Benchmark
on:
  push:
      branches:
        - master

jobs:
  benchmark:
    runs-on: [self-hosted, benchmarker, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build CrazyCanvas Production
        uses: IbexOmega/lambda-build-action@v1.0.2
        with:
          project-path: CrazyCanvas/CrazyCanvas.vcxproj
          build-configuration: Production x64_StaticLib

      - name: Benchmark
        run: python .github/workflows/benchmark.py --bin .\Build\bin\Production-windows-x86_64-x64_StaticLib\CrazyCanvas\CrazyCanvas.exe

      - name: Update Charts
        run: python .github/workflows/update-charts.py
        env:
          PAT: ${{ secrets.DOCS_PAT }}
